### ISSUE TITLE
TODO for Finish

### ISSUE THREAD

**Issue by leonkaspers** [leonkaspers/Hangman#8]
- [x] Game Funktioniert 
- [x] - Einheitliche Sprache DEUTSCH 
- [x] - Skalierung (Schrittgröße, grafikgroße)
- [x] - _ _ _ _ _  GROOOOOOOOßßßßßß
- [x] - Help bzw. HILFE button in menüleiste 
- [x] - Gamestates vereinheitlichen Grafik bzw. game states vereinheitlichen (grafik -1)
- [x] - Verdächtige Kommentare entfernen und unverdächtige hinzufügen
- [x] - Black screen bei Reset
- [x] - Farben anpassen, Background und so
- [x] - hangman schriftzug screens 
- [x] - Figur soll stehen bei gewinn
- [x] - Restet des _ _ _ _ _ _  Panel und bei start schon anzeigen 
- [x] - Scope doc nachgucken
- [x] wenn game over kann man weiterklicken zu sieg bildschirm
- [x] es ist möglich mehrmals den gleichen buchstaben einzugeben -> input sollte auf used gecheck werden -> fehlertextfeld
- [x] Felder in NewGUI static machen falls man die nicht ändern muss
- [x] Koordinaten der Figur nach oben setzten

- [x] - Game Klasse umstrukturieren

+++
- [x] - Menüfuhrung für modi ( Worteingabe hinzufügen bzw. Rein schreiben das das geht) aber passwort funk. das Punkte kommen
- [x] - Leerzeilen automatisch aussortieren und und nicht eingegeben werden müssen
